### ISSUE TITLE
 英语是没有书名号的，title.yml里的英语书名不应该加书名号《》

### ISSUE THREAD

**Issue by xiaopangju** [PercyDan54/RandomTitle#2]
英语是没有书名号的，title.yml里的英语书名不应该加书名号《》

_Originally posted by @xiaopangju in https://github.com/PercyDan54/RandomTitle-Fabric/pull/1#issuecomment-797453413_

**Comment by PercyDan54** [comment]
还不如直接把所有中文句子删了
没必要
