### ISSUE TITLE
[BUG] 1.17.1 Fabric0.12.12 Crashed

### ISSUE THREAD

**Issue by ffffffffawd** [PercyDan54/RandomTitle#3]
**Describe the bug:** 
Just is add this MOD, The Minecraft not working.
**Minecraft version:** 
1.17.1 Fabric0.12.12 Fabric API0.45.1
**Logs / crash reports:**
https://pastebin.com/PfcqZ3rq

Why me not in MCBBS report this bug?
去你的绑定手机号

**Comment by PercyDan54** [comment]
请尝试移除其他mod再启动并发送日志

**Comment by ffffffffawd** [comment]
好

**Comment by ffffffffawd** [comment]
https://pastebin.com/TFR333vK
还是崩溃，不显示窗口直接没了
焯

**Comment by ffffffffawd** [comment]
尝试过JDK17和JDK16

**Comment by PercyDan54** [comment]
下载这个版本试试
MCBBS传的应该已经修了，GitHub没更新
不能发Jar就套了层zip，记得解压
[RandomTitle-Fabric-1.0.7.zip](https://github.com/PercyDan54/RandomTitle/files/7875038/RandomTitle-Fabric-1.0.7.zip)

**Comment by ffffffffawd** [comment]
感谢

**Comment by ffffffffawd** [comment]
成功启动

**Comment by ffffffffawd** [comment]
十分感谢

**Comment by ffffffffawd** [comment]
但。。。貌似和氢不兼容
https://pastebin.com/FRGbVLBP

**Comment by ffffffffawd** [comment]
![image](https://user-images.githubusercontent.com/87227557/149624088-c80f7bac-a0e5-4b43-8c41-9d41a2a30cdd.png)

**Comment by PercyDan54** [comment]
优化mod兼容性一直是问题，尤其是对游戏核心做更改的mod来说
我不解决兼容性问题

**Comment by ffffffffawd** [comment]
az

**Comment by ffffffffawd** [comment]
算了直接删了氢

**Comment by ffffffffawd** [comment]
e
ModManger也不兼容
这个MOD没有改核心
[MCMOD](https://www.mcmod.cn/class/4998.html)

**Comment by ffffffffawd** [comment]
[latest.log](https://github.com/PercyDan54/RandomTitle/files/7875087/latest.log)

**Comment by PercyDan54** [comment]
这个Mod[对Minecraft.class做了更改](https://github.com/PercyDan54/RandomTitle/blob/master/src/main/java/me/PercyDan/RandomTitle/Mixins/MixinMinecraft.java)，因为设置标题的代码在那里

还是那句话，我没有能力也不解决兼容性问题

**Comment by ffffffffawd** [comment]
焯
现在无论如何都不能打开我的游戏了
删了randontitle都不行

**Comment by PercyDan54** [comment]
兼容性问题请自行解决

**Comment by ffffffffawd** [comment]
其实
PercyDan你的模组兼容性已经很好了
100个模组没有一个冲突的
是我着急了
对不起
