### ISSUE TITLE
[CRASH] RandomTitle and PixelmonReforged9.0.0 cannot be loaded.

### ISSUE THREAD

**Issue by Akita041** [PercyDan54/RandomTitle#4]
Describe:
The client will crash when the RandomTitle and PokemonReforge9.0.0 are loaded together.
However, any one between the two mods can be loaded normally when placed in the client.

Minecraft Version:1.16.5
ForgeVersion:1.16.5 - 36.2.35
Links to Poké mon Mods: [http](https://reforged.gg)

The crash report is as follows:
[crash-2022-05-25_12.54.08-fml.txt](https://github.com/PercyDan54/RandomTitle/files/8768054/crash-2022-05-25_12.54.08-fml.txt)
:

**Comment by PercyDan54** [comment]
Please try removing either that mod's or RandomTitle's `org.yaml` folder.

The mod is way too big for me to download
Seems both of the mods embedded the YAML library and had a conflict
![image](https://user-images.githubusercontent.com/50285552/170188181-1043e6ff-6331-4573-85b5-90a490f8a792.png)

**Comment by Akita041** [comment]
I tried this and deleted randomtitle's org Yaml folder, but it did not start successfully, and even the loading interface will crash directly.
That mods may need VPN. I uploaded it to the 360 network disk. This is the download address of mod
Link below:
https://yunpan.360.cn/surl_y23tS2Yhywz

**Comment by PercyDan54** [comment]
> I tried this and deleted randomtitle's org Yaml folder, but it did not start successfully, and even the loading interface will crash directly. That mods may need VPN. I uploaded it to the 360 network disk. This is the download address of mod Link below: https://yunpan.360.cn/surl_y23tS2Yhywz

Try removing `PokemonReforge` 's yaml and restore RandomTitle's yaml instead?

**Comment by 1844808678** [comment]
Sorry, I can't do that. This will directly cause the game window to fail to open and start

**Comment by 1844808678** [comment]
Sorry, I can't do that. This will directly cause the game window to fail to open and start

**Comment by Akita041** [comment]
RandomTitle is a very good mod, but it will be unusable in the client with pixelmon reforged 9.0.0 mods. Thank the author for his enthusiastic answer. I will feed back the problem to pixelmon mod Team and hope they can solve this problem.

**Comment by Akita041** [comment]
thanks
