### ISSUE TITLE
[BUG] 1.19无法正常工作

### ISSUE THREAD

**Issue by china-us** [PercyDan54/RandomTitle#5]
**Describe the bug:*在1.19无法正常工作

**Minecraft version:*1.19

**Logs / crash reports:*

**Comment by PercyDan54** [comment]
有无日志

**Comment by PercyDan54** [comment]
https://github.com/PercyDan54/RandomTitle/releases/tag/1.0.7-1.19

**Comment by china-us** [comment]
现在已经正常工作在1.19的fabric了 感谢
