### ISSUE TITLE
[BUG] 1.19.2+工作不正常

### ISSUE THREAD

**Issue by safesaffawa** [PercyDan54/RandomTitle#6]
**Describe the bug:** 
在1.19.2是正常 1.19.3开始就不正常了 :D

**Minecraft version:** 
1.19.2+

**Logs / crash reports:**
没有日志 因为只是不显示随机的内容

**Comment by safesaffawa** [comment]
[minecraft-exported-logs-2023-06-07T19-05-12.log](https://github.com/PercyDan54/RandomTitle/files/11676241/minecraft-exported-logs-2023-06-07T19-05-12.log)
这是hmcl的日志（1.19.3 :D)

**Comment by PercyDan54** [comment]
Mojang在1.19.3开始大规模重写游戏......😅
PercyDan54/BorderRemover#11
只能说寄

**Comment by PercyDan54** [comment]
[RandomTitle-Fabric-1.0.7.jar.zip](https://github.com/PercyDan54/RandomTitle/files/11677442/RandomTitle-Fabric-1.0.7.jar.zip)
放一个修了的到这里
